# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_auto_20181102_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_publish'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
